### PR TITLE
Added average on HORIZONTAL, VERTICAL, and QUARTER skins.

### PR DESCRIPTION
**Pull request by claudio-rosati**

### CODE REVIEW

**Comment by claudio-rosati** [comment]
I've forgot AMP... so please wait before merging this pull request.

**Comment by claudio-rosati** [comment]
Too late ;-)

**Comment by HanSolo** [comment]
:)

**Comment by claudio-rosati** [comment]
I've not started codit it, so not a big problem, I'll do another pull request

**Pull request merged**
