### PR TITLE
Dashboard thresholdtext

### PR DESCRIPTION
**Pull request by adrianromero**
This pull request adds a threshold label for DashboardSkin in a similar way of KPISkin. Two small topics about this pull request.

* If threshold is near the min value or max value the label goes out the gauge dimensions. I did not want to modify the whole skin to make this label fit and in my pet project this is not a problem.
* I am modifiying the text labe in the resize() method of DashboardSkin. KPISkin modifies the text label in the redraw method(). The reason is that changing the threshold fires only the resize event and if it is done in redraw method the label is not updated. KPISkin has this problem.

### CODE REVIEW

**Comment by adrianromero** [comment]
Example:

dashboardthresholdtext

**Comment by HanSolo** [comment]
I'm not a big fan of having the threshold text outside of the gauge (also don't really like it in the KpiSkin). So I moved it to the inside of the arc instead. Also fixed a problem related to the background color.

**Comment by HanSolo** [comment]
Btw you might want to make a copy of the DashboardSkin, rename it and then you can modify it as much as you like. You can set the skin by simple calling gauge.setSkin(new YOUR_SKIN(gauge)), this might be easier for you to modify it in the way you like :)

**Comment by adrianromero** [comment]
Yes. I will create my own skin based on the DashboardSkin

Thanks for the sugestion

**Pull request closed without merging**
